### ISSUE TITLE
Bug: Exception on calculating XP gained.

### ISSUE THREAD

**Issue by JayTurnr** [TrainerDex/TrainerDex-RedCog#11]
Case: [Trainer 45](http://www.ekpogo.uk/api/trainer/trainers/45/) excepted. About 5 records show in API call.

```
 [09/10/2017 12:59] ERROR red on_command_error 369: Exception in command 'update xp'
 Traceback (most recent call last):
   File "lib/discord/ext/commands/core.py", line 50, in wrapped
     ret = yield from coro(*args, **kwargs)
   File "/opt/red/cogs/trainerdex.py", line 236, in xp
     embed = await self.updateCard(trainer)
   File "/opt/red/cogs/trainerdex.py", line 99, in updateCard
     dailyDiff = await self.getDiff(trainer, 1)
   File "/opt/red/cogs/trainerdex.py", line 65, in getDiff
     latest = updates[0]
 IndexError: list index out of range
```

Case: JayTurnr
Just didn't show XP gained at all. Failed if statement?

**Comment by JayTurnr** [comment]
Can confirm that this is an issue. It seems to not show XP gain for some trainers, but cause a bug for other trainers. I've yet to confirm the source of the bug but I have a suspicion that Trainer.updates() is returning the list in the wrong order. Also, list is cut short to 14 days, some users don't update for months. This is due to API requests timing out the bot. 

This is unneeded, the object parser just needs to be re-jiggled to accept input direct from a dict rather than explicitly making a request each time

**Comment by JayTurnr** [comment]
All fixed!
